### ISSUE TITLE
Add Editor's Pick Feature

### ISSUE THREAD

**Issue by tonyohhmg** [themorganthompson/ratemyshot#16]
Create a private space for author's to choose one "Editor's Pick" photo for user's submissions.

ratemyshot.co/admin

Layout should be same as main page of application with the addition of a selection control on each user's photo to select that as the Editor's Pick.

Enable Save selection.

**Comment by themorganthompson** [comment]
Add "Editors' Pick" ribbon to home page card

**Comment by themorganthompson** [comment]
https://github.com/themorganthompson/ratemyshot/pull/22
