### ISSUE TITLE
Update Info Icon in Top Nav

### ISSUE THREAD

**Issue by tonyohhmg** [themorganthompson/ratemyshot#17]
Update icon for "Info" in top nav.

See attached for correct icon.![info-24px.svg](https://images.zenhubusercontent.com/5eb439f4520c845d691f6c39/3a95a44c-7188-4387-8306-f62789809aff)

**Comment by themorganthompson** [comment]
Fixed in https://github.com/themorganthompson/ratemyshot/commit/2415609af538d0d18766a1c4f5366a636ca54edd
