### ISSUE TITLE
Add Copyright/Version/Links Footer

### ISSUE THREAD

**Issue by tonyohhmg** [themorganthompson/ratemyshot#20]
Add footer with following content:

Copyright
Version #
Privacy Policy
Help

**Comment by tonyohhmg** [comment]
![Footer.png](https://images.zenhubusercontent.com/5eb439f4520c845d691f6c39/64c427cf-3f46-433b-b98a-abfd5284302c)

**Comment by themorganthompson** [comment]
![Screen Shot 2020-05-12 at 9.09.17 AM.png](https://images.zenhubusercontent.com/5cb70f3f8a3a7251ef0bd9a3/ffd13f83-fd24-40ff-8c90-d680dec71099)

**Comment by themorganthompson** [comment]
https://github.com/themorganthompson/ratemyshot/pull/23
