### ISSUE TITLE
Action Modal for Rating Posts

### ISSUE THREAD

**Issue by themorganthompson** [themorganthompson/ratemyshot#25]
https://artive.invisionapp.com/public/share/FM15LR58UB#/screens/478071256

**Comment by tonyohhmg** [comment]
To add Blue Info Box at top of modal to inform user of no updating or editing allowed after saving critique.

**Comment by tonyohhmg** [comment]
https://material-ui.com/components/alert/#simple-alerts

**Comment by tonyohhmg** [comment]
Add label "Critiqued" to photo details modal.

**Comment by themorganthompson** [comment]
@tonyohhmg where does it go and what does the critiqued label look like
