### ISSUE TITLE
Set up hello@artive.co

### ISSUE THREAD

**Issue by tonyohhmg** [themorganthompson/ratemyshot#51]
Create and set up hello@artive.co email address.

**Comment by tonyohhmg** [comment]
Set up hello@artive.co to forward to anthonyorsa@gmail.com and contact@themorganthompson.com.

**Comment by themorganthompson** [comment]
@tonyohhmg is this temporary or did you create a real domain email?

**Comment by tonyohhmg** [comment]
@themorganthompson yea, it's a temporary email forward from hello@artive.co to anthonyorsa@gmail.com and contact@themorganthompson.com. Let's set up a real email account once we push an official BETA out. We can use the email forward for now to push to private BETA testers, family, etc.
