### ISSUE TITLE
Remove reCaptcha Badge from Login Screen

### ISSUE THREAD

**Issue by tonyohhmg** [themorganthompson/ratemyshot#60]
.grecaptcha-badge { visibility: hidden; }

**Comment by themorganthompson** [comment]
<img width="1483" alt="Screen Shot 2020-06-01 at 10 10 11 AM" src="https://user-images.githubusercontent.com/6472893/83417460-1fd8c580-a3f0-11ea-8554-442b176e6b8f.png">
